PYTHON ?= python3

# https://docutils.sourceforge.io/docs/ref/rst/directives.html#replace
print_directive := printf '.. |%s| replace:: %s\n'

includedir := doc/include
metadatafile := $(includedir)/metadata.rst
defaultsfile := $(includedir)/defaults.txt

datadir := data
mandir := $(datadir)/share/man/man1


doc: manpages

manpages: $(mandir)/logfilter.1.gz

$(metadatafile): doc/logfilter.1.rst logfilter.py | $(includedir)
	echo ".. This file generated by Make" > $@
	$(print_directive) version \
		$$($(PYTHON) \
		-c 'import logfilter; print(logfilter.__version__)') \
		>> $@
	$(print_directive) date \
		$$(git log -1 --pretty=format:%cs doc/logfilter.1.rst) \
		>> $@

$(defaultsfile): logfilter.py | $(includedir)
	$(PYTHON) \
		-c 'import logfilter; \
		    {print(f"{k} = {v}") for k,v in logfilter.DEFAULTS.items()}' \
		> $(defaultsfile)

$(includedir):
	mkdir $(includedir)

$(mandir)/logfilter.1.gz: doc/logfilter.1.rst $(metadatafile) $(defaultsfile) | $(mandir)
	rst2man --config=doc/docutils.conf $< \
		| gzip -9 > $@

$(mandir):
	mkdir -p $(mandir)

clean:
	rm -rf $(includedir) $(datadir)

lint: pylint mypy

pylint:
	pylint $$(git ls-files '*.py')

mypy:
	mypy --strict logfilter.py
	mypy test

# This target runs tests that only depend on the standard library.
test:
	$(PYTHON) -m doctest logfilter.py
	$(PYTHON) test/test_logfilter.py

.PHONY: doc manpages clean lint pylint mypy test
