[tox]
requires =
    tox>=4.22
env_list =
    py{39,310,311,312,313,314,315}
    mypy
    pylint-py311

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
dependency_groups =
    test
commands =
    pytest {tty:--color=yes} {posargs}

[testenv:mypy]
description = type check with mypy
skip_install = true
dependency_groups =
    test
deps =
    mypy
commands =
    mypy {posargs:logfilter.py test}

[testenv:pylint-py311]
# A Python <=3.11 is required.
description = lint source with Pylint
skip_install = true
dependency_groups =
    test
deps =
    -r requirements/pylint.requirements.txt
commands =
    pylint {posargs:logfilter.py test}

[testenv:bootstrap]
description = make manpages for including in sdist
skip_install = true
deps =
    docutils
allowlist_externals = make
commands =
    make {posargs:manpages}
